server:
  port: 8081

spring:
  application:
    name: ms-autenticacion
  datasource:
    url: jdbc:mysql://localhost:3306/db_vetnova_auth?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "VetNovaSecretKeySuperSeguraParaMicroservicios2026++"
  expiration: 86400000